version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host  # Use host network mode
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000  # Now resolves to host's localhost:8000